Implement ECDH
golang-fips/openssl-fips pull request #45
Opened 2022-12-20 13:11 UTC by qmuntal

This PR implements the ECDH functions.

@derekparker @ueno I haven't ported `SharedKeyECDH` function. For what I can see, it was only used to support OpenSSL ECDH on `crypto/tls`. Go1.20 implements ECDH using the new `crypto/ecdh` package, so it would be easier for you to just use the ECDH functions from this PR than trying to retrofit `SharedKeyECDH`. Please correct me if I'm wrong, in which case I'll try to port it.

2023-01-03 18:17 UTC, derekparker commented
@simo5 @ueno thoughts on the non-usage of EVP? I know in recent internal discussions the use of deprecated (e.g. non-EVP) functionality poses issues to FIPS compliance on our end.

2023-01-03 19:15 UTC, simo5 commented
@derekparker yes, I think this code needs to be rewritten

Because of the following issues:
1) uses legacy EC_KEY objects
   should used EVP_PKEY and initialize it with EV_PKEY_fromdata()
2) Implements ECDH
   this is definitely not ok FIPS wise
   it should use EVP_PKEY_derive()
3) curveSize() should probably be replaced by either EVP_PKEY_size(), EVP_PKEY_bits() or EVP_PKEY_security_bits()  
4) GenerateKeyECDH should use EVP_PKEY_keygen()

2023-01-03 19:16 UTC, simo5 requested changes
See comment left, this code is definitely not FIPS compliant

2023-01-03 19:27 UTC, qmuntal commented
Thanks @simo5 for the details. I'll work on fixing your points.

2023-01-19 18:09 UTC, derekparker commented
@qmuntal any updates on this?

2023-01-19 19:33 UTC, qmuntal commented
> @qmuntal any updates on this?

Yep, but I'm first doing the work on our repo so we can land the changes on msft go1.20: https://github.com/microsoft/go-crypto-openssl/pull/44

Once I'm done with it I'll port it here.

2023-01-19 21:32 UTC, derekparker commented
> > @qmuntal any updates on this?
> 
> Yep, but I'm first doing the work on our repo so we can land the changes on msft go1.20: [microsoft/go-crypto-openssl#44](https://github.com/microsoft/go-crypto-openssl/pull/44)
> 
> Once I'm done with it I'll port it here.

Ack, sounds good, thanks for the update!

2023-01-24 16:58 UTC, qmuntal commented
> Because of the following issues:
> 
> 1. uses legacy EC_KEY objects
>    should used EVP_PKEY and initialize it with EV_PKEY_fromdata()
> 2. Implements ECDH
>    this is definitely not ok FIPS wise
>    it should use EVP_PKEY_derive()
> 3. curveSize() should probably be replaced by either EVP_PKEY_size(), EVP_PKEY_bits() or EVP_PKEY_security_bits()
> 4. GenerateKeyECDH should use EVP_PKEY_keygen()

@simo5 I've improved this PR with most of your suggestions. The only thing missing is dropping `EC_KEY` usage on OpenSSL 3, but this is quite complex because some Go functions return the raw `EC_KEY`. On the other hand, I've managed to isolate the `EC_POINT` and `EC_GROUP` related functions to just OpenSSL 1.0.2.
I would prefer to tackle the `EC_KEY` issue for OpenSSL 3 in another PR, as it also affects RSA and ECDSA functions.

2023-01-24 17:21 UTC, simo5 commented
The ECDH function now uses the correct EVP interfaces, but given the EVP_PKEYs are still wrapping legacy EC_KEYs the code is not going to use the correct internal APIs, legacy (non-fips) APIs will still be used.

What I am perplexed about is GenerateKeyECDH(), you create a key through the correct EVP interface ... but then still pull ou an EC_KEY from it nad return a raw key in bytes .... why??

2023-01-24 17:28 UTC, qmuntal commented
> What I am perplexed about is GenerateKeyECDH(), you create a key through the correct EVP interface ... but then still pull ou an EC_KEY from it nad return a raw key in bytes .... why??

The Go boring bindings expect the raw key in bytes:

https://github.com/golang/go/blob/dc9d219cad115cf04d07a0cd10a46d127cf6e5e1/src/crypto/ecdh/nist.go#L38-L45

> The ECDH function now uses the correct EVP interfaces, but given the EVP_PKEYs are still wrapping legacy EC_KEYs the code is not going to use the correct internal APIs, legacy (non-fips) APIs will still be used.

I'll give it another shot.

2023-01-24 18:55 UTC, simo5 commented
> > What I am perplexed about is GenerateKeyECDH(), you create a key through the correct EVP interface ... but then still pull ou an EC_KEY from it nad return a raw key in bytes .... why??
> 
> The Go boring bindings expect the raw key in bytes:
> 
> https://github.com/golang/go/blob/dc9d219cad115cf04d07a0cd10a46d127cf6e5e1/src/crypto/ecdh/nist.go#L38-L45

Uggh, ok.

> 
> > The ECDH function now uses the correct EVP interfaces, but given the EVP_PKEYs are still wrapping legacy EC_KEYs the code is not going to use the correct internal APIs, legacy (non-fips) APIs will still be used.
> 
> I'll give it another shot.

EVP_PEKY_fromdata() should make the code as easy as the current one hopefully.

2023-01-26 17:32 UTC, simo5 commented
Nice work!

2023-01-26 17:37 UTC, qmuntal commented
> Nice work!

Thanks, it has been quite a challenge 😅 I've been able to remove all `EC_KEY_*` functions from the OpenSSL 3 path and EVP_PKEYs that don't wrap legacy keys.

Still open to suggestions!

2023-01-31 16:44 UTC, qmuntal commented
@derekparker this is ready for another ound of reviews.

2023-01-31 17:20 UTC, simo5 approved these changes
I think we are in much better shape wrt FIPS interfaces now.

2023-01-31 23:32 UTC, dagood approved these changes
A few suggestions, but LGTM either way.

2023-01-31 23:32 UTC, dagood commented on openssl/ecdh.go
> +	return
Seeing these split had me second guessing this, but I checked, and this behaves the same per [spec](https://go.dev/ref/spec#Return_statements):

```suggestion
	return newEVPPKEY(key)
```

2023-02-02 14:45 UTC, qmuntal commented on openssl/params.go
> +		key:         key,
Done!

2023-02-02 15:18 UTC, merged